[
    {
        id: 1,
        firstName: "Евгений", 
        lastName: "Петров", 
        avatarUrl: "https://скачать-другвокруг.рф/wp-content/uploads/2018/11/avatarka-7.jpg", 
        city: "Москва",
        country: "Россия",
        posts: [],
        about: {}, 
        photos: [], 
        videos: [], 
        friends: [],
    },
    { 
        id: 2,
        firstName: "Никита",
        lastName: "Васильков",
        avatarUrl: "https://i.pinimg.com/236x/d5/2c/bd/d52cbdbba8c008534b0455363050aaf8.jpg",
        city: "Смоленск",
        country: "Россия",
        posts: [],
        about: {}, 
        photos: [], 
        videos: [], 
        friends: [],
    },
    { 
        id: 3, firstName: "Света",
        lastName: "Варфоломеева",
        avatarUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQSlM_szRqtHV2qjh-Uq0DXmdV-m0XYC0B8pA&usqp=CAU",
        city: "Новосибирск",
        country: "Россия",
        posts: [],
        about: {}, 
        photos: [], 
        videos: [], 
        friends: [],
    },
    { 
        id: 4, 
        firstName: "Саня", 
        lastName: "Долгополов", 
        avatarUrl: "https://avatarko.ru/img/kartinka/1/multfilm_gomer.png",
        city: "Екатеринбург",
        country: "Россия",
        posts: [],
        about: {}, 
        photos: [], 
        videos: [], 
        friends: [],
    },
    { 
        id: 5,
        firstName: "Дмитрий",
        lastName: "Бродягин",
        avatarUrl: "https://static10.tgstat.ru/channels/_0/de/deeb9f0e7b43dc6d67f4628356c274d7.jpg",
        city: "Берлин",
        country: "Германия",
        posts: [],
        about: {}, 
        photos: [], 
        videos: [], 
        friends: [],
    },
    { 
        id: 6,
        firstName: "Юлия",
        lastName: "Никитина",
        avatarUrl: "http://sun9-17.userapi.com/impg/rrEXhuJKKJNUz738_jeY0w6iJHPUrUZiv-OiJw/2qoHnCsxJz4.jpg?size=483x604&quality=96&sign=c3da779fb28b22f1d4ce5c744416539a&type=album",
        city: "Минск",
        country: "Беларусь",
        posts: [],
        about: {}, 
        photos: [], 
        videos: [], 
        friends: [],
    },
    {
        id: 7,
        firstName: "Игнат",
        lastName: "Копылов",
        avatarUrl: "https://s.starladder.com/uploads/user_logo/5/c/9/d/meta_tag_1039d807e6e9d7e403ecd6510eb61d83.jpg",
        city: "Мазабука",
        country: "Замбия",
        posts: [],
        about: {}, 
        photos: [], 
        videos: [], 
        friends: [],
    },
    {
        id: 8,
        firstName: "Александра",
        lastName: "Тимофеева",
        avatarUrl: "https://trikky.ru/wp-content/blogs.dir/1/files/2020/06/10/d9b97b5646fbb691e29947a921049a1d.jpg",
        city: "Риффа",
        country: "Риффа",
        posts: [],
        about: {}, 
        photos: [], 
        videos: [], 
        friends: [],
    },
    {
        id: 9,
        firstName: "Игорь",
        lastName: "Воробьев Игорь",
        avatarUrl: "https://vraki.net/sites/default/files/inline/images/1_6.png",
        city: "Praia Grande",
        country: "Бразилия",
        posts: [],
        about: {}, 
        photos: [], 
        videos: [], 
        friends: [],
    },
    {
        id: 10,
        firstName: "Алексей",
        lastName: "Горелов",
        avatarUrl: "https://m.the-flow.ru/uploads/images/origin/00/79/45/33/18/8f6fb4c.jpg",
        city: "Памплона",
        country: "Испания",
        posts: [],
        about: {}, 
        photos: [], 
        videos: [], 
        friends: [],
    },
    {
        id: 11,
        firstName: "Ксения",
        lastName: "Харитонова",
        avatarUrl: "https://99px.ru/sstorage/41/2020/01/image_411501201853056789306.jpg",
        city: "Santiago de Compostela",
        country: "Испания",
        posts: [],
        about: {}, 
        photos: [], 
        videos: [], 
        friends: [],
    },
    {
        id: 12,
        firstName: "Варвара",
        lastName: "Носова",
        avatarUrl: "https://i.pinimg.com/736x/c7/2a/3f/c72a3f3d7938658422132659f4f40b3b.jpg",
        city: "Мадхепур",
        country: "Индия",
        posts: [],
        about: {}, 
        photos: [], 
        videos: [], 
        friends: [],
    },
    {
        id: 13,
        firstName: "Артемий",
        lastName: "Ермолаев",
        avatarUrl: "https://vjoy.cc/wp-content/uploads/2020/11/bezymyannyja-28.jpg",
        city: "Анджар",
        country: "Индия",
        posts: [],
        about: {}, 
        photos: [], 
        videos: [], 
        friends: [],
    },
    {
        id: 14,
        firstName: "Михаил",
        lastName: "Беляев",
        avatarUrl: "https://hsto.org/webt/5c/27/25/5c27253946def422312371.png",
        city: "Dashitou",
        country: "Китай",
        posts: [],
        about: {}, 
        photos: [], 
        videos: [], 
        friends: [],
    },
    {
        id: 15,
        firstName: "Анна",
        lastName: "Смирнова",
        avatarUrl: "https://phbl.xyz/wp-content/uploads/2009/01/407/Vika_sp-650x405.png",
        city: "Мбандака",
        country: "Конго",
        posts: [],
        about: {}, 
        photos: [], 
        videos: [], 
        friends: [],
    },
    {
        id: 16,
        firstName: "Амина",
        lastName: "Богданова",
        avatarUrl: "https://thypix.com/wp-content/uploads/2021/10/manga-profile-picture-9-700x700.jpg",
        city: "Аньяма",
        country: "Кот-д'Ивуар",
        posts: [],
        about: {}, 
        photos: [], 
        videos: [], 
        friends: [],
    },
    {
        id: 17,
        firstName: "Даниил",
        lastName: "Соловьев",
        avatarUrl: "https://images.stopgame.ru/uploads/images/295881/form/2018/03/22/1521735132.png",
        city: "Кабимас",
        country: "Венесуэла",
        posts: [],
        about: {}, 
        photos: [], 
        videos: [], 
        friends: [],
    },
    {
        id: 18,
        firstName: "Михаил",
        lastName: "Марков",
        avatarUrl: "https://i.pinimg.com/originals/c7/29/6d/c7296d22d448887838b35bf41dc223ba.jpg",
        city: "Нюрнберг",
        country: "Германия",
        posts: [],
        about: {}, 
        photos: [], 
        videos: [], 
        friends: [],
    },
]