[
    { 
        id: 1, 
        firstName: "Евгений", 
        lastName: "Петров", 
        avatarUrl: "https://скачать-другвокруг.рф/wp-content/uploads/2018/11/avatarka-7.jpg", 
        city: "Москва",
        country: "Россия",
        status: "С некоторыми людьми встреча в этой жизни была лишней",
        friendshipStartDate: "2021-09-26",
        followed: true, 
     },
    { 
        id: 2,
        firstName: "Никита",
        lastName: "Васильков",
        avatarUrl: "https://i.pinimg.com/236x/d5/2c/bd/d52cbdbba8c008534b0455363050aaf8.jpg",
        city: "Смоленск",
        country: "Россия",
        status: "Муж, обозвавший жену жирной коровой, на полгода вместе с ней сел на строгую диету",
        friendshipStartDate: "2021-10-01",
        followed: true, 
    },
    { 
        id: 3, firstName: "Света",
        lastName: "Варфоломеева",
        avatarUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQSlM_szRqtHV2qjh-Uq0DXmdV-m0XYC0B8pA&usqp=CAU",
        city: "Новосибирск",
        country: "Россия",
        status: "Хочешь увеличить грудь? макни её в растишку!",
        friendshipStartDate: "2021-10-29",
        followed: true, 

    },
    { 
        id: 4, 
        firstName: "Саня", 
        lastName: "Долгополов", 
        avatarUrl: "https://avatarko.ru/img/kartinka/1/multfilm_gomer.png",
        city: "Екатеринбург",
        country: "Россия",
        status: "Принять мужчину таким какой он есть, может только военкомат.",
        friendshipStartDate: "2021-10-30",
        followed: true, 
    },
    { 
        id: 5,
        firstName: "Дмитрий",
        lastName: "Бродягин",
        avatarUrl: "https://static10.tgstat.ru/channels/_0/de/deeb9f0e7b43dc6d67f4628356c274d7.jpg",
        city: "Берлин",
        country: "Германия",
        status: "Ничто не ограничивает твои действия так, как фраза 'делай что хочешь'…",
        friendshipStartDate: "2021-11-12",
        followed: true, 
    },
    { 
        id: 6,
        firstName: "Юлия",
        lastName: "Никитина",
        avatarUrl: "http://sun9-17.userapi.com/impg/rrEXhuJKKJNUz738_jeY0w6iJHPUrUZiv-OiJw/2qoHnCsxJz4.jpg?size=483x604&quality=96&sign=c3da779fb28b22f1d4ce5c744416539a&type=album",
        city: "Минск",
        country: "Беларусь",
        status: "Выйти замуж за IT-шника – это одно, а жить с ним – совсем другое.",
        friendshipStartDate: "2021-12-12",
        followed: true, 
    },
    {
        id: 7,
        firstName: "Игнат",
        lastName: "Копылов",
        avatarUrl: "https://s.starladder.com/uploads/user_logo/5/c/9/d/meta_tag_1039d807e6e9d7e403ecd6510eb61d83.jpg",
        city: "Мазабука",
        country: "Замбия",
        status: "Маленький мальчик порнуху смотрел. Фильма не понял, но очень вспотел",
        friendshipStartDate: "2021-12-12",
        followed: true,
    },
    {
        id: 8,
        firstName: "Александра",
        lastName: "Тимофеева",
        avatarUrl: "https://trikky.ru/wp-content/blogs.dir/1/files/2020/06/10/d9b97b5646fbb691e29947a921049a1d.jpg",
        city: "Риффа",
        country: "Риффа",
        status: "Труд есть одно из непременных условий искусства дожить до ста лет.",
        friendshipStartDate: "2020-01-09",
        followed: false,
    },
    {
        id: 9,
        firstName: "Игорь",
        lastName: "Воробьев Игорь",
        avatarUrl: "https://vraki.net/sites/default/files/inline/images/1_6.png",
        city: "Praia Grande",
        country: "Бразилия",
        status: " Кто трудится только для себя, уподобляется скоту, набивающему брюхо. Достойный трудится для человечества.",
        friendshipStartDate: "2020-02-28",
        followed: false,
    },
    {
        id: 10,
        firstName: "Алексей",
        lastName: "Горелов",
        avatarUrl: "https://m.the-flow.ru/uploads/images/origin/00/79/45/33/18/8f6fb4c.jpg",
        city: "Памплона",
        country: "Испания",
        status: "Вдвойне тяжелее переносить обиды со стороны тех людей, от которых мы всего менее вправе ожидать их.",
        friendshipStartDate: "2020-07-29",
        followed: false,
    },
    {
        id: 11,
        firstName: "Ксения",
        lastName: "Харитонова",
        avatarUrl: "https://99px.ru/sstorage/41/2020/01/image_411501201853056789306.jpg",
        city: "Santiago de Compostela",
        country: "Испания",
        status: "Никогда не удается быть таким счастливым, как в те часы, когда работа не оставляет ни минуты свободной.",
        friendshipStartDate: "2022-01-21",
        followed: false,
    },
    {
        id: 12,
        firstName: "Варвара",
        lastName: "Носова",
        avatarUrl: "https://i.pinimg.com/736x/c7/2a/3f/c72a3f3d7938658422132659f4f40b3b.jpg",
        city: "Мадхепур",
        country: "Индия",
        status: "В любой профессии любовь к ней является одним из условий успеха, но это особенно справедливо для научно-исследовательской работы.",
        friendshipStartDate: "2020-10-27",
        followed: false,
    },
    {
        id: 13,
        firstName: "Артемий",
        lastName: "Ермолаев",
        avatarUrl: "https://vjoy.cc/wp-content/uploads/2020/11/bezymyannyja-28.jpg",
        city: "Анджар",
        country: "Индия",
        status: " Любая страсть всегда все преувеличивает, иначе она не была бы страстью.",
        friendshipStartDate: "2019-12-20",
        followed: false,
    },
    {
        id: 14,
        firstName: "Михаил",
        lastName: "Беляев",
        avatarUrl: "https://hsto.org/webt/5c/27/25/5c27253946def422312371.png",
        city: "Dashitou",
        country: "Китай",
        status: "Маленький мальчик порнуху смотрел. Фильма не понял, но очень вспотел",
        friendshipStartDate: "2021-09-10",
        followed: true,
    },{
        id: 15,
        firstName: "Анна",
        lastName: "Смирнова",
        avatarUrl: "https://phbl.xyz/wp-content/uploads/2009/01/407/Vika_sp-650x405.png",
        city: "Мбандака",
        country: "Конго",
        status: "Если бы мы все обладали разумною гордостью, в мире не было бы столько мерзостей.",
        friendshipStartDate: "2019-10-15",
        followed: false,
    },
    {
        id: 16,
        firstName: "Амина",
        lastName: "Богданова",
        avatarUrl: "https://thypix.com/wp-content/uploads/2021/10/manga-profile-picture-9-700x700.jpg",
        city: "Аньяма",
        country: "Кот-д'Ивуар",
        status: "Идеальная красота, самая восхитительная наружность ничего не стоят, если ими никто не восхищается.",
        friendshipStartDate: "2019-12-05",
        followed: true,
    },
    {
        id: 17,
        firstName: "Даниил",
        lastName: "Соловьев",
        avatarUrl: "https://images.stopgame.ru/uploads/images/295881/form/2018/03/22/1521735132.png",
        city: "Кабимас",
        country: "Венесуэла",
        status: " Счастлив тот, кто, слыша хулу себе, может ею воспользоваться для исправления.",
        friendshipStartDate: "2020-04-03",
        followed: false,
    },
    {
        id: 18,
        firstName: "Михаил",
        lastName: "Марков",
        avatarUrl: "https://i.pinimg.com/originals/c7/29/6d/c7296d22d448887838b35bf41dc223ba.jpg",
        city: "Нюрнберг",
        country: "Германия",
        status: " Глупость не была бы подлинной глупостью, если бы не боялась ума.",
        friendshipStartDate: "2018-12-24",
        followed: false,
    },
]